name: Name testing

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node: [14,16]
    steps: 
      - uses: actions/setup-node@v4
      with: 
        node-versions: ${{ matrix.node }} 